baseurl = "/"
languageCode = "en-us"
title = "The Dusty Cottage"
theme = "hugo-theme-casper"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Butchirvings"
  authorlocation = "Australia"
  authorwebsite = "http://dustycottage.netlify.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = ""
  #githubName = ""
  #twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"

[[menu.main]]
  name = "Dusty Cottage Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"
